### ISSUE TITLE
Not fire in component

### ISSUE THREAD

**Issue by robertnicjoo** [axenox/onscan.js#12]
Hi,

I know that this is not package for any kind of JS framework but i'm trying to use it in `VueJs` while I'm getting the console results (not as i defined them) I cannot access them some how.

# Code

```javascript
mounted() {
    this.getScanner; // load my function when page starts (loads)
},
methods: {
    getScanner() { // scan function
        onScan.attachTo(document, {
            ignoreIfFocusOn: 'input',
            onScan: function (sCode, iQty) { // Alternative to document.addEventListener('scan')
                console.log('Scanned: ' + iQty + 'x ' + sCode); // not printing in console
            },
            onKeyDetect: function(iKeyCode, oEvent){
                console.log('1', iKeyCode) // not printing in console
                console.log('2', oEvent) // not printing in console
            },
        });

        // Register event listener
        // document.addEventListener('scan', function(sScancode, iQuatity) {
        //     alert('qty', iQuantity + 'x ' + 'scan', sScancode);
        //     console.log('scan', sScancode); // did not print in console
        //     console.log('qty', iQuantity);  // did not print in console
        // });
    },
}
```

**Screenshot**

![01](https://user-images.githubusercontent.com/8672823/80305733-ddb4d680-87e8-11ea-9ee5-813c4e52b24b.png)

As you can see what I get in console isn't include any code that i defined! 

I'm supposed to get 3 data in my console beginning with `Scanned` , `1` , `2`. What I get isn't include those (not sure where it even comes from 😄 )

**Any idea?**

**Comment by kabachello** [comment]
It looks like your focus was in the JS Console when you triggered the scans, not on the page. Click anywhere on your page (except inputs) and scan again. Your setup seems OK.
