### ISSUE TITLE
problem with IPDA030 android 7.0

### ISSUE THREAD

**Issue by marsiliflavio** [axenox/onscan.js#18]
Hi,
i have tested with https://ithinkwise.com/onscanjs/ playgroud but the barcode not working.
options:
Scanner Settings: 
{"scanButtonKeyCode":false,
"scanButtonLongPressTime":500,
"timeBeforeScanTest":100,
"avgTimeByChar":40,
"minLength":2,
"suffixKeyCodes":[9,13],
"prefixKeyCodes":[],
"ignoreIfFocusOn":false,
"stopPropagation":false,
"preventDefault":false,
"reactToKeydown":true,
"reactToPaste":true,
"singleScanQty":1,
"reactToKeyDown":true}

response:
message: Received code is shorted then minimal length, scanCode:, scanDuration: 0, avgTimeByChar:50, minLength:2

thanks

**Comment by kabachello** [comment]
Please activate onKeyDetect in the playground to see if any key events are detected at all. Built-in scanners typically have different scan modes. If you don't see any character codes with the onKeyDetect-option active, you probably have the wrong scan model in the scanners config. Look for something like "keyboard wedge" or similar. You can find more information about the configuration of scanners here: https://a.kabachnik.info/onscan-js.html

**Comment by marsiliflavio** [comment]
Thanks,
stupidly I hadn't checked the "keyboard simulation" setting on device.

F.
