### ISSUE TITLE
[Question] Is it possible to get hardware details?

### ISSUE THREAD

**Issue by uzumakinaruto123** [axenox/onscan.js#23]
Is it possible to get hardware details(model/unique id)?

Scenario: Having multiple scanners connected to different ports and on scan identifying which scanner scanned the bar code or port from which it was scanned, 

Looking for some unique information based on device or port.

**Comment by Heisenberg74** [comment]
Hi,

I am not sure it is possible to get hardware details as scanner acts as keyboard with onscan.js 

But one trick is to program the device to add a prefix which will be unique per device.

I use Zebra DS2208 scanners and 123scan software to setup it.

**Comment by uzumakinaruto123** [comment]
Yes, had to do that scanner configuration! Will close this.
