### ISSUE TITLE
ignoreIfFocusOn doen't seem to work

### ISSUE THREAD

**Issue by arwinvdv** [axenox/onscan.js#4]
Version: 1.3.1

I try to make sure that the scanned barcode never is put in a input field. So it only is printed in the console. I have set the `ignoreIfFocusOn` to `'input'` but that does nothing. I also have set the `preventDefault` to `true` but then I cannot type anything in the input field by myself. Is it possible to have an input field that the user only can fill in by them selfs and that the scanned barcodes only go to the console?

Used code:
```
HTML:
<input type="text" id="input-postalcode" class="form-control form-control-lg" placeholder="postalcode" required autofocus>

JS:
onScan.attachTo(document, {
    ignoreIfFocusOn: 'input',
    onScan: function (sCode, iQty) { // Alternative to document.addEventListener('scan')
      console.log('Scanned: ' + iQty + 'x ' + sCode);
    },
});
```
Result:
Barcode is visible in the input field after scan.

**Comment by kabachello** [comment]
Fixed in 1.3.2.
